"""Initial migration

Revision ID: 87c16773c51d
Revises:
Create Date: 2025-02-06 13:28:46.195988

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '87c16773c51d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoiceproducts',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('invoice_id', 'product_id')
    )
    op.add_column('invoice', sa.Column('payment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'invoice', 'payment', ['payment_id'], ['id'])
    op.drop_constraint('fk_payment_product', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'product', ['product_id'], ['id'])
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'full_name')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('fk_payment_product', 'payment', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'payment_id')
    op.drop_table('invoiceproducts')
    # ### end Alembic commands ###
